name: Tim Penner Music
favicon: null
layout_spectrum: 0.42301
typography_spectrum: 0.53504
title: Tim Penner Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2cfd0'
    - '#0f0b0a'
    - '#ff99bd'
    - '#ff0059'
    - '#a34d4b'
  brandStrength: 0.625
  lightness: 0.0625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
