name: Tim Penner Music
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53504
title: Tim Penner Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#afafaf'
    - '#7f7f7f'
    - '#2f2f2f'
  brandStrength: 0.625
  lightness: 0.0625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
